routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Monolog\Handler\RotatingFileHandler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// Auth::routes();

//************************************************//
//****************** CMS-ADMIN *******************//
//************************************************//

// Route::view('/', 'cms.admin.parent')->name('admin.blocked');

Route::prefix('cms/admin/')->middleware('auth:admin')->group(function () {

    Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
    }
    });



Route::resource('admin', 'AdminController');
Route::put('status/{id}','OrderController@editstatus')->name('status.order');
Route::resource('general', 'GeneralController');
Route::put('/changepaswword/{id}', 'AdminController@password')->name('admin.password');
Route::get('user/details/{details}','UserController@userdetails')->name('user.details');
Route::get('/serves/all','ServeController@all')->name('ser.all');

Route::resource('user', 'UserController');
Route::resource('setting', 'SettingController');
Route::resource('comp', 'CompanyController');
// Route::get('comp/all','DashController@all')->name('comp.all');

Route::resource('product', 'ProductController');
Route::get('','dashController@admin')->name('admin.dashbord');
Route::get('/ublode','dashController@orderublode')->name('order.ublode');
Route::get('logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
Route::get('/selectuser/{id}', 'ContactController@selectuser')->name('select.user');



});
//************************************************//
//****************** CMS-ADMIN----User *******************//
//************************************************//
Route::get('/user/month/{file}','dashController@usermonth')->middleware('auth:admin,user')->name('user.month');
Route::resource('category', 'CategoryController')->middleware('auth:admin,user');
Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin')->name('details.month');
// Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin,user')->name('details.month');
Route::get('/categoryproducts/{id}','CategoryController@CategoryProduct')->middleware('auth:admin,user')->name('category.product');
Route::post('details/data','OrderProductController@detailsdata')->middleware('auth:admin,user')->name('details.data');
Route::resource('details', 'orderProductController')->middleware('auth:admin,user');
Route::get('downloadorder/{file}','ImageController@downloadorder')->middleware('auth:admin,user')->name('daw.order');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');

Route::resource('product', 'ProductController')->middleware('auth:admin,user');
Route::resource('ser', 'ServeController')->middleware('auth:admin,user');

Route::get('downloadproduct/{file}','ImageController@downloadproduct')->middleware('auth:admin,user')->name('daw.product');
Route::get('contactresiver/','ContactController@contactresever')->middleware('auth:admin,user')->name('contact.resiver');


Route::resource('order', 'OrderController')->middleware('auth:admin,user');
Route::resource('image', 'ImageController')->middleware('auth:admin,user');
Route::resource('about', 'AboutController')->middleware('auth:admin,user');
Route::resource('contact', 'ContactController')->middleware('auth:admin,user');

////////////////////////////





Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
Route::get('login', 'AdminAuthController@showLoginView')->name('admin.login.view');
Route::post('login', 'AdminAuthController@login')->name('admin.login.post');
Route::view('blocked', 'cms.admin.blocked')->name('cms.admin.blocked');
});


//************************************************//
//****************** CMS-User *******************//
//************************************************//
Route::prefix('cms/user/')->middleware('auth:user')->group(function () {


 Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
       }
       });
Route::get('about','AboutController@userabout')->name('user.about');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');
Route::Post('searchuser','DashController@searchuser')->middleware('auth:user')->name('search.user');

Route::view('/create', 'cms.user.orders.create');
Route::put('/changepaswword/{id}', 'UserController@password')->name('user.password');
Route::view('/changepassword','cms.user.password')->name('user.view.changepassword');
Route::get('','dashController@user')->name('user.dashbord');
Route::get('logout', 'Auth\UserAuthController@logout')->name('user.logout');
Route::get('user/profile','DashController@userprofile')->name('user.profile');
Route::put('user/edit/user/{file}','DashController@edituser')->name('edit.profile');
Route::view('/editprfile','cms.user.editprofile')->name('edit.user.view');
    });


Route::prefix('cms/user/')->namespace('Auth')->group(function () {



Route::get('login', 'UserAuthController@showLoginView')->name('user.login.view');
Route::post('login', 'UserAuthController@login')->name('user.login.post');
Route::view('blocked', 'cms.user.blocked')->name('user.blocked');
Route::get('/register','RegisterControllerUser@reguser')->name('reg.user.view');
Route::post('/post/register','RegisterControllerUser@reguserpost')->name('reg.user.post');

 });

Route::post('/cms/user/searchorder','ProductController@getcode')->name('get.come')->middleware('auth:user');
// Route::post('/user/test','dashController@test')->name('user.test')->middleware('auth:user');
//////////////////////////////////////////////////////////////////////////
Route::get('','WebController@cms')->name('web.index');

Route::get('/comp/all', 'CompanyController@all')->middleware('auth:admin')->name('comp.all');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
    public function user(){
        return $this->belongsTo(User::class,'user_id','id');
    }

     public function admin(){
     return $this->belongsTo(Admin::class,'admin_id','id');
     }




}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Contact;
use App\Notifications\ContactNotification;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::guard('user')->check()){
            if ((Auth::user()->setting->vedio=='Visible')&&(Auth::user()->general->vedio=='Visible')){

            $contacts=Auth::user()->contact()->where('tybesender','user')->get();
            return view('cms.user.contacts.index',['contacts'=>$contacts]);
        }

            else
            return redirect()->route('user.dashbord');
        }
        if (Auth::guard('admin')->check()) {
            $contacts = Auth::user()->contact()->where('tybesender', 'admin')->get();
            return view('cms.admin.contacts.index', ['contacts' => $contacts]);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        if(Auth::guard('user')->check()){
                        if ((Auth::user()->setting->vedio=='Visible')&&(Auth::user()->general->vedio=='Visible')){

            return view('cms.user.contacts.create');}
            else{
                return redirect()->route('user.dashbord');
            }
        }
        if(Auth::guard('admin')->check()){
            $userid=0;
            $users=User::all();
            return view('cms.admin.contacts.create',['users'=>$users,'userid'=>$userid]);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // dd($request->get('resever'));
        if(Auth::guard('user')->check()){
            if ((Auth::user()->setting->vedio=='InVisible')||(Auth::user()->general->vedio=='InVisible')){
             Alert::warning('ليس لديك صلاحية', 'فشلت العملية');
             return redirect()->route('user.dashbord');

            }
        }
                $request->validate([
                    'subject'=>'required|string|max:45',
                    'articale'=>'required|string',
                    'image'=>'image',
                ],[

                    'subject.required'=>'العنوان فارغ',
                    'subject.max'=>'يجب  تقليل عدد حروف العنوان',
                    'articale.required'=>'الموضوع فارغ',
                    'image.image'=>'يجب أن تكون صورة'
                ]);
                $contact=new Contact();
                $contact->subject=$request->get('subject');
                $contact->articale=$request->get('articale');
                 if($request->hasFile('image')){
                 $imagefile=$request->file('image');
                 $imagename=time().' '.$request->name.' '.' '.$imagefile->getClientOriginalName();

                 $imagefile->move('images/contacts',$imagename);
                 $contact->image=$imagename ;
                 }
                 if(Auth::guard('user')->check()){

                $contact->tybesender='user';
                $contact->tyberesever='admin';
                $contact->user_id=Auth::user()->id;
                $contact->admin_id=1;




                 }
                 else{
                    if(!($request->resever)){
                             $request->session()->flash('status','alert-danger');
                             $request->session()->flash('message','الرجاء اختيار مسوق');
                             return redirect()->back()->withInput();
                    }
                     $contact->tybesender='admin';
                     $contact->tyberesever='user';
                     $contact->user_id=$request->resever;
                     $contact->admin_id=Auth::user()->id;

                 }

                 $save=$contact->save();
                 if(Auth::guard('user')->check()){

                    $admins=Admin::all();
                    $name='رسالة جديدة';
                    $note=new ContactNotification($contact,$name);
                    for ($i=0; $i <count($admins) ; $i++) {

                        $admins[$i]->notify($note);
                        }

                 }
                 else
                 {


                     $user=User::findOrFail($request->resever);
                     $name='رسالة جديدة';

                     $note=new ContactNotification($contact,$name);
                     $user->notify($note);
                 }

                 if($save){
                     $request->session()->flash('status','alert-success');
                     $request->session()->flash('message','تم إرسال الرسالة بنجاح');
                    return redirect()->back();
                 }





    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        if(Auth::guard('user')->check()){
    if(!((Auth::user()->setting->vedio=='InVisible')||(Auth::user()->general->vedio=='InVisible'))){
            return view('cms.user.contacts.show',['contact'=>Contact::find($id)]);
        }}

        if (Auth::guard('admin')->check()) {
            // dd(45);
            return view('cms.admin.contacts.show', ['contact' => Contact::find($id)]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        if(Auth::guard('admin')->check()){


        $request->validate([
            'replay'=>'required|string'
        ],[
            'replay.required'=>'الرد فارغ'
        ]);
            // dd(33223);
        $contact=Contact::with('user')->findOrFail($id);
        $contact->replay=$request->get('replay');
        $save=$contact->save();
        if($save){
            $user=$contact->user;
            $name='رد جديد';
            $note=new ContactNotification($contact,$name);
            $user->notify($note);

        Alert::success('تم إضافة الرد  بنجاح', 'نجحت العملية');
        return redirect()->back();
        }}


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if(Auth::guard('admin')->check()){


           $del=Contact::destroy($id);
           if ($del){
           return response()->json(['icon'=>'success','title'=>'  تم الحذف بنجاح'],200);
           }else{
           return response()->json(['icon'=>'error','title'=>'Deleted Post failed'],400);
           }
        }

    }

    public function selectuser($id){

          $users=User::all();
        return view('cms.admin.contacts.create',['users'=>$users,'userid'=>$id]);
    }
    public function contactresever(){

        if(Auth::guard('user')->check()){
        $contacts=Auth::user()->contact()->where('tybesender','admin')->get();
        return view('cms.user.contacts.index',['contacts'=>$contacts]);
        }
        if (Auth::guard('admin')->check()) {
            $contacts = Auth::user()->contact()->where('tybesender', 'user')->get();
            return view('cms.admin.contacts.index', ['contacts' => $contacts]);
        }

    }
}

resources/views/cms/admin/contacts/create.blade.php
@extends('cms.admin.parent')
@section('title','التواصل')
@section('content')
 <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h2>Inbox</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.dashbord')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.show',[Auth::user()->id])}}">الصفحة الشخصية</a></li>
                            <li class="breadcrumb-item active" style="font-size: 20px" aria-current="page">   </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="mail-inbox">
                            <div class="mobile-left">
                                <a href="javascript:void(0);" class="btn btn-primary toggle-email-nav"><i class="fa fa-bars"></i></a>
                            </div>

                            <div class="body mail-right check-all-parent">
                                <div class="mail-compose">
                                <form action="{{route('contact.store')}}" method="POST" enctype="multipart/form-data">
                                       @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </div>
                        @endif
                        @if (session()->has('message'))
                                        <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                             role="alert">
                                            <span> {{ session()->get('message') }}</span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                         @endif
                                    @csrf

                                    {{-- <input type="text" cols="40" rows="20"  class="form-control"> --}}
                                    {{-- <textarea name="" id="" cols="30" rows="10"></textarea> --}}
                                     <div class="form-group">
                                            <label style="font-size: 20px" >العنوان</label>
                                            <input type="text" class="form-control" value="{{old('subject')}}" style="font-size: 20px" name="subject" placeholder="الرجاء ادخال العنوان">
                                        </div>
                                           <div class="form-group">
                                            <label style="font-size: 20px">المستقبل</label>
                                             <div class="col-md-12 col-sm-10">
                                             <select class="form-control input-height" name="resever" >
                                            <option value="">Select...</option>
                                           @foreach ($users as $item)
                                        <option style="font-size: 20px" @if(old('resever')||$userid==$item->id) selected @endif value="{{$item->id}}">{{$item->name}}</option>

                                           @endforeach
                                        </select>
                                    </div>
                                </div>

                                        <div class="form-group">
                                            <label style="font-size: 20px" >الموضوع</label>

                                       <textarea name="articale" class="form-control" id="" cols="30" rows="10">{{old('articale')}}</textarea>
                                        </div>
                                         <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file"  width="590px" height="390px" class="dropify" name="image">
                                            </div>

                                        </div>

                                    <div class="m-t-30 text-right">
                                        <button type="submit" class="btn btn-success btn-round">إرسال</button>

                                         </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </div>
    </div>

@endsection

resources/views/cms/admin/contacts/index.blade.php
@extends('cms.admin.parent')
@section('title','كافة الرسائل')
@section('content')

<div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>الرسائل  </h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a  style="font-size: 20px" href="{{route('admin.dashbord')}}">الصفحة الرئيسية</a></li>
                            <li class="breadcrumb-item active" style="font-size: 20px" aria-current="page">الرسائل</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="table-responsive">
                        <table class="table table-hover table-custom spacing5">
                            <thead>
                                <tr>
                                    {{-- <th>#</th> --}}
                                    <th>#</th>
                                    <th>عرض</th>
                                    <th>الموضوع</th>
                                    <th>الحالة</th>
                                     <th>المرسل</th>
                                    <th>وقت الإرسال</th>
                                    <th>الحذف</th>


                                </tr>
                            </thead>
                            <tbody>
                            <span hidden>{{$i=0}}</span>
                                @foreach ($contacts as $item)
                            <span hidden>{{++$i}}</span>
                                <tr>
                                    {{-- <td class="w60">
                                        <img src="../assets/images/xs/avatar1.jpg" data-toggle="tooltip" data-placement="top" title="" alt="Avatar" class="w35 rounded" data-original-title="Avatar Name">
                                    </td> --}}
                                <td><span class="list-name">{{$i}}</span></td>
                                  <td>  <a href="{{route('contact.show',[$item->id])}}"><span style="font-size: 17px" class="badge badge-warning"><i class="icon-user"></i> عرض</span></a>   </td>
                                    <td>{{$item->subject}}</td>
                                    <td>
                                        @if($item->replay)

                                        <span class="badge badge-success">تم الرد</span>
                                        @else
                                        <span class="badge badge-danger">لم يتم الرد</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if($item->tybesender=='admin')
                                    <span class="badge badge-info">admin</span>
                                        @else
                                    <span class="badge badge-info">{{$item->user->name}}</span>
                                        @endif
                                    </td>
                                <td>{{$item->created_at->diffForHumans()}}</td>
                                <td>
                                <a onclick="confirmDelete(this, '{{$item->id}}')" type="button" style="font-size: 20px" class="btn btn-sm btn-default js-sweetalert" title="حذف" data-type="confirm"><i class="fa fa-trash-o text-danger"> حذف </i></a>
                                </td>
                                </tr>
                                @endforeach


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deletecontact(app, id)
                }
            })
        }

        function deletecontact(app, id) {
            axios.delete('/contact/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>

@endsection

resources/views/cms/admin/contacts/show.blade.php
@extends('cms.admin.parent')
@section('title','الرسالة')
@section('content')
 <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h2>الرسالة</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.dashbord')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.show',[Auth::user()->id])}}">الصفحة الشخصية</a></li>
                            <li class="breadcrumb-item active"  style="font-size: 20px" aria-current="page">الرسائل</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
        <div class="container">
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12">
                    <div class="single-blog">

                        <div class="post-content overflow">
                        <h1 class="post-title " ><a href="#">الموضوع</a></h1>
                        <h2 class="post-title bold"><a href="#">{{$contact->subject}}</a></h2>
                        <p style="font-size: 17px">{{$contact->articale}}</p>

                        </div>

                        <div class="post-thumb">
                            @if($contact->image)
                        <a href="#"><img src="{{url('images/contacts/'.$contact->image)}}" class="img-fluid rounded" alt="Techno Band"></a>
                       @endif
                    </div>

                    </div>
                    <hr>

                    @if($contact->replay&&$contact->tybesender=='user')
                 <span class="badge badge-success">تم الرد</span>
                            <div class="post-content overflow">
                        <p style="font-size: 17px">{{$contact->replay}}</p>
                        </div>
                        @else
                    <span class="badge badge-danger">لم يتم الرد</span>

                        @endif

                        <div class="post-content overflow">
                            @if($contact->tybesender=='user')
                        <h2 style="color: black" ><a href="#">المرسل</a></h2>
                        <small>{{$contact->created_at}}</small>
                        <h1 class="post-title " ><a href="#">{{$contact->user->name}}</a></h1>

                        @else
                        <h2  style="color: black" ><a href="#">المستقبل</a></h2>
                        <small>{{$contact->created_at}}</small>
                        <h1  class="post-title bold"><a href="#">{{$contact->user->name}}  </a></h1>
                            @endif

                        </div>
                        {{-- <small>تم الإنشاء</small><br> --}}
                    {{-- <small>{{$contact->creates_at}}</small> --}}
                                <hr>
                                @if($contact->replay)
                                <h1>تم الرد</h1>
                                <p>{{$contact->replay}}</p>

                                            @else

                    <form action="{{route('contact.update',[$contact->id])}}" method="POST">
                        @csrf
                        @method("PUT")



                                             <div class="form-group">
                                            <label style="font-size: 20px" >اضف ردك</label>
                                       <textarea name="replay" class="form-control" id="" cols="30" rows="10">{{old('replay')}}</textarea>
                                        </div>

                                    <div class="m-t-30 text-right">
                                        <button type="submit" class="btn btn-success btn-round">إرسال</button>

                                         </form>


                                        @endif
                </div>
            </div>
        </div>
    </div>
@endsection