routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Monolog\Handler\RotatingFileHandler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// Auth::routes();

//************************************************//
//****************** CMS-ADMIN *******************//
//************************************************//

// Route::view('/', 'cms.admin.parent')->name('admin.blocked');

Route::prefix('cms/admin/')->middleware('auth:admin')->group(function () {

    Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
    }
    });



Route::resource('admin', 'AdminController');
Route::put('status/{id}','OrderController@editstatus')->name('status.order');
Route::resource('general', 'GeneralController');
Route::put('/changepaswword/{id}', 'AdminController@password')->name('admin.password');
Route::get('user/details/{details}','UserController@userdetails')->name('user.details');
Route::get('/serves/all','ServeController@all')->name('ser.all');

Route::resource('user', 'UserController');
Route::resource('setting', 'SettingController');
Route::resource('comp', 'CompanyController');
// Route::get('comp/all','DashController@all')->name('comp.all');

Route::resource('product', 'ProductController');
Route::get('','dashController@admin')->name('admin.dashbord');
Route::get('/ublode','dashController@orderublode')->name('order.ublode');
Route::get('logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
Route::get('/selectuser/{id}', 'ContactController@selectuser')->name('select.user');



});
//************************************************//
//****************** CMS-ADMIN----User *******************//
//************************************************//
Route::get('/user/month/{file}','dashController@usermonth')->middleware('auth:admin,user')->name('user.month');
Route::resource('category', 'CategoryController')->middleware('auth:admin,user');
Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin')->name('details.month');
// Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin,user')->name('details.month');
Route::get('/categoryproducts/{id}','CategoryController@CategoryProduct')->middleware('auth:admin,user')->name('category.product');
Route::post('details/data','OrderProductController@detailsdata')->middleware('auth:admin,user')->name('details.data');
Route::resource('details', 'orderProductController')->middleware('auth:admin,user');
Route::get('downloadorder/{file}','ImageController@downloadorder')->middleware('auth:admin,user')->name('daw.order');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');

Route::resource('product', 'ProductController')->middleware('auth:admin,user');
Route::resource('ser', 'ServeController')->middleware('auth:admin,user');

Route::get('downloadproduct/{file}','ImageController@downloadproduct')->middleware('auth:admin,user')->name('daw.product');
Route::get('contactresiver/','ContactController@contactresever')->middleware('auth:admin,user')->name('contact.resiver');


Route::resource('order', 'OrderController')->middleware('auth:admin,user');
Route::resource('image', 'ImageController')->middleware('auth:admin,user');
Route::resource('about', 'AboutController')->middleware('auth:admin,user');
Route::resource('contact', 'ContactController')->middleware('auth:admin,user');

////////////////////////////





Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
Route::get('login', 'AdminAuthController@showLoginView')->name('admin.login.view');
Route::post('login', 'AdminAuthController@login')->name('admin.login.post');
Route::view('blocked', 'cms.admin.blocked')->name('cms.admin.blocked');
});


//************************************************//
//****************** CMS-User *******************//
//************************************************//
Route::prefix('cms/user/')->middleware('auth:user')->group(function () {


 Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
       }
       });
Route::get('about','AboutController@userabout')->name('user.about');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');
Route::Post('searchuser','DashController@searchuser')->middleware('auth:user')->name('search.user');

Route::view('/create', 'cms.user.orders.create');
Route::put('/changepaswword/{id}', 'UserController@password')->name('user.password');
Route::view('/changepassword','cms.user.password')->name('user.view.changepassword');
Route::get('','dashController@user')->name('user.dashbord');
Route::get('logout', 'Auth\UserAuthController@logout')->name('user.logout');
Route::get('user/profile','DashController@userprofile')->name('user.profile');
Route::put('user/edit/user/{file}','DashController@edituser')->name('edit.profile');
Route::view('/editprfile','cms.user.editprofile')->name('edit.user.view');
    });


Route::prefix('cms/user/')->namespace('Auth')->group(function () {



Route::get('login', 'UserAuthController@showLoginView')->name('user.login.view');
Route::post('login', 'UserAuthController@login')->name('user.login.post');
Route::view('blocked', 'cms.user.blocked')->name('user.blocked');
Route::get('/register','RegisterControllerUser@reguser')->name('reg.user.view');
Route::post('/post/register','RegisterControllerUser@reguserpost')->name('reg.user.post');

 });

Route::post('/cms/user/searchorder','ProductController@getcode')->name('get.come')->middleware('auth:user');
// Route::post('/user/test','dashController@test')->name('user.test')->middleware('auth:user');
//////////////////////////////////////////////////////////////////////////
Route::get('','WebController@cms')->name('web.index');

Route::get('/comp/all', 'CompanyController@all')->middleware('auth:admin')->name('comp.all');

app/Serve.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Serve extends Model
{
    //
}

app/Http/Controllers/ServeController.php
<?php

namespace App\Http\Controllers;

use App\Serve;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class ServeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $d=Serve::all();
        // dd($d);
        if(Auth::guard('admin')->check()){


        return view('cms.admin.serves.index',['images'=>Serve::all()]);
    }
        if(Auth::guard('user')->check()){
                    return view('cms.user.serves.index',['images'=>Serve::where('status','Visible')->get()]);

        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
                if(Auth::guard('admin')->check()){

        if(Auth::guard('admin')->check()){
        return view('cms.admin.serves.create');
        }

        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd(32);
                if(Auth::guard('admin')->check()){

        $request->validate([
            'name'=>'required|string|min:5',
            'image'=>'required|image',
            'status'=>'in:on',

        ],[
            'name.required'=>'العنوان مطلوب',
            'name.min'=>'العنوان أفل من 5 حروف',
            'image.image'=>'يجب أن يكون الملف عبارة عن صورة'
        ]);
        $ser=new Serve();
        $ser->name=$request->get('name');
        $ser->status=$request->get('status')=='on'?'Visible':'InVisible';
         if($request->hasFile('image')){
         $imagefile=$request->file('image');
         $imagename=time().' '.$request->name.' '.' '.$imagefile->getClientOriginalName();

         $imagefile->move('images/serves',$imagename);
         $ser->image=$imagename ;
         }
         $save=$ser->save();
         if($save){
                     Alert::success('تم الإنشاء بنجاح', 'نجحت العملية');
                return redirect()->back();
         }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Serve  $serve
     * @return \Illuminate\Http\Response
     */
    public function show(Serve $serve)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Serve  $serve
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
                if(Auth::guard('admin')->check()){

        return view('cms.admin.serves.edit',['serve'=>Serve::find($id)]);
                }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Serve  $serve
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        if(Auth::guard('admin')->check()){


           $request->validate([
           'name'=>'required|string|min:5',
           'status'=>'in:on',

           ],[
           'name.required'=>'العنوان مطلوب',
           'name.min'=>'العنوان أفل من 5 حروف',
           ]);
           $ser=Serve::findOrFail($id);
           $ser->name=$request->get('name');
           $ser->status=$request->get('status')=='on'?'Visible':'InVisible';
           if($request->hasFile('image')){
           $imagefile=$request->file('image');
           $imagename=time().' '.$request->name.' '.' '.$imagefile->getClientOriginalName();

           $imagefile->move('images/serves',$imagename);
           $ser->image=$imagename ;
           }
           $save=$ser->save();
           if($save){
           Alert::success('تم التعديل بنجاح', 'نجحت العملية');
           return redirect()->back();
           }}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Serve  $serve
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del=Serve::destroy($id);

         if ($del){
         return response()->json(['icon'=>'success','title'=>'تم الحذف بنجاح '],200);
         }else{
         return response()->json(['icon'=>'error','title'=>'Deleted Post failed'],400);
         }

    }
    public function all(){
        $serves=Serve::all();
        return view('cms.admin.serves.all',['serves'=>$serves]);
    }
}

resources/views/cms/admin/serves/all.blade.php
@extends('cms.admin.parent')
@section('title','servess')

@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}" style="font-size: 20px">الرئيسية</a></li>
                            <li class="breadcrumb-item " style="font-size: 20px" aria-current="page">الميزات</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{route('ser.create')}}" class="btn btn-sm btn-primary" title="">ميزة جديدة</a>
                        {{-- <a href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507" class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a> --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="header">
                            <h2 style="font-size: 20px">الميزات</h2>

                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5 mb-0">
                                <thead>
                                    <tr>
                                        <th >#</th>
                                          <th style="font-size: 17px"> عنوان الميزة</th>
                                        <th style="font-size: 17px">صورة الميزة</th>
                                        <th style="font-size: 17px">حالة الفئة</th>
                                        <th style="font-size: 17px">الإعدادات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <span hidden>{{$i=0}}</span>
                                    @foreach ($serves as $item)
                                <span hidden>{{$i++}}</span>

                                    <tr>
                                    <td>{{$i}}</td>


                                    <td><span style="font-size: 17px">{{$item->name}}</span></td>
                                            <td class="w60">
                                            <img src="{{url('images/serves/'.$item->image)}}" data-toggle="tooltip" data-placement="top" title="Avatar Name" alt="Avatar" class="w35 h35 rounded">
                                        </td>
                                     <td>
                                         @if($item->status=='Visible')
                                        <span style="font-size: 17px" class="badge badge-success">نشطة</span>
                                        @else
                                    <span style="font-size: 17px" class="badge badge-danger">متوقفة</span>
                                        @endif

                                    </td>
                                        <td>
                            <a href="{{route('ser.edit',[$item->id])}}" type="button" style="font-size: 20px" class="btn btn-sm btn-default" title="تعديل"><i class="fa fa-edit"></i> تعديل</a>
                                        <a onclick="confirmDelete(this, '{{$item->id}}')" type="button" style="font-size: 20px" class="btn btn-sm btn-default js-sweetalert" title="حذف" data-type="confirm"><i class="fa fa-trash-o text-danger"> حذف </i></a>


                                        </td>




                                        {{-- <td>
                                            <a href="javascript:void(0);" class="btn btn-info btn-round">Interview</a>

                                        </td> --}}
                                    </tr>
                                         @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deleteserves(app, id)
                }
            })
        }

        function deleteserves(app, id) {
            axios.delete('/ser/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>

@endsection

resources/views/cms/admin/serves/create.blade.php
@extends('cms.admin.parent')
@section('title','الميزات')

@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1 style="font-size: 20px"> الميزات</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}" style="font-size: 20px">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="{{route('ser.index')}}" style="font-size: 20px">الميزات</a></li>
                            <li class="breadcrumb-item active" aria-current="page"style="font-size: 20px"> ميزة جديدة</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                       {{-- <a href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507" class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a> --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                        <form method="POST" action="{{route('ser.store')}}" enctype="multipart/form-data">


                            @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </div>
                        @endif
                        @if (session()->has('message'))
                                        <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                             role="alert">
                                            <span> {{ session()->get('message') }}</span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endif
                            @csrf
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">

                                        <div class="form-group">
                                            <label style="font-size: 20px" >عنوان الميزة</label>
                                        <input type="text" class="form-control" value="{{old('name')}}" style="font-size: 20px" name="name" placeholder=" ادخل الإسم رباعي ">
                                        </div>





                                         <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file"  width="590px" height="390px" class="dropify" name="image">
                                            </div>

                                        </div>


                            <div class="form-group">
                                <label style="font-size: 20px">حالة الفئة</label>
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" name="status"
                                        id="status"
                                        @if((old('status')) == 'on') checked @endif>
                                    <label class="custom-control-label" style="font-size: 20px" for="status">تفعيل</label>

                        </div>
                    </div>






                                    </div>
                                </div>
                                <div>
                                            <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> تسجيل  </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cms/admin/serves/edit.blade.php
@extends('cms.admin.parent')
@section('title','تعديل ميزة')

@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1 style="font-size: 20px"> تعديل ميزة</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}" style="font-size: 20px">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="{{route('ser.index')}}" style="font-size: 20px">الميزات</a></li>
                            <li class="breadcrumb-item"><a href="{{route('ser.create')}}" style="font-size: 20px">ميزة جديدة </a></li>

                            <li class="breadcrumb-item active" aria-current="page"style="font-size: 20px"> تعديل ميزة</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                       {{-- <a href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507" class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a> --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                        <form method="POST" action="{{route('ser.update',[$serve->id])}}" enctype="multipart/form-data">


                            @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </div>
                        @endif
                        @if (session()->has('message'))
                                        <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                             role="alert">
                                            <span> {{ session()->get('message') }}</span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endif
                            @csrf
                            @method("PUT")
                            <div  style="align-content: center" class="col-lg-2 col-md-12 center text-center">
                        <div class="body text-center">
                        <img class="img-thumbnail rounded-circle" src="{{url('images/serves/'.$serve->image)}}" alt="{{$serve->name}}">
                            <h6 class="mt-3">{{$serve->name}}</h6>
                        </div>
                </div>
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">



                                        <div class="form-group">
                                            <label style="font-size: 20px" >الإسم</label>
                                        <input type="text" class="form-control" value="{{$serve->name}}" style="font-size: 20px" name="name" placeholder=" ادخل الإسم رباعي ">
                                        </div>




                                            <label style="font-size: 20px" >  الميزة</label>

                                         <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file" width="590px" height="390px" class="dropify" name="image">
                                            </div>

                                        </div>



                            <div class="form-group">
                                <label style="font-size: 20px">حالة عرض الميزة</label>
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" name="status"
                                        id="status"
                                        @if($serve->status == 'Active') checked @endif>
                                    <label class="custom-control-label" style="font-size: 20px" for="status">مُفعل</label>

                        </div>
                    </div>

                                    </div>
                                </div>
                                <div>
                                            <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> تعديل  </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cms/admin/serves/index.blade.php
@extends('cms.admin.parent')
@section('title',' الميزات')

@section('content')
    <div id="main-content">
        <div class="container">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h2>الميزات</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('ser.all')}}">تعديل الميزات</a></li>
                            <li class="breadcrumb-item"><a  style="font-size: 20px" href="{{route('admin.show',[Auth::user()->id])}}">الرئيسية</a></li>
                            <li class="breadcrumb-item active" style="font-size: 20px" aria-current="page">صور </li>
                            </ol>
                        </nav>
                    </div>
                            <div class="col-md-6 col-sm-12 text-right hidden-xs">
                            <a href="{{route('ser.create')}}" class="btn btn-sm btn-primary btn-round" title=""><i class="fa fa-cloud-upload"></i> ميزة جديدة</a>
                        </div>
                </div>
            </div>

            <div id="lightgallery" class="row clearfix lightGallery">
                @foreach ($images as $item)
                     <div class="col-lg-3 col-md-6 m-b-30"><a class="light-link" href="{{url('images/serves/'.$item->image)}}"><img class="img-fluid rounded"  style="height: 380px"  src="{{url('images/serves/'.$item->image)}}" alt=""></a></div>
                @endforeach

            </div>
        </div>
    </div>
@endsection
@section('script')

<script src="{{asset('cms/html/assets/js/pages/medias/image-gallery.js')}}"></script>
<script src="{{asset('cms/html/assets/bundles/lightgallery.bundle.js')}}"></script><!-- Light Gallery Plugin Js -->

@endsection