routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Monolog\Handler\RotatingFileHandler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// Auth::routes();

//************************************************//
//****************** CMS-ADMIN *******************//
//************************************************//

// Route::view('/', 'cms.admin.parent')->name('admin.blocked');

Route::prefix('cms/admin/')->middleware('auth:admin')->group(function () {

    Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
    }
    });



Route::resource('admin', 'AdminController');
Route::put('status/{id}','OrderController@editstatus')->name('status.order');
Route::resource('general', 'GeneralController');
Route::put('/changepaswword/{id}', 'AdminController@password')->name('admin.password');
Route::get('user/details/{details}','UserController@userdetails')->name('user.details');
Route::get('/serves/all','ServeController@all')->name('ser.all');

Route::resource('user', 'UserController');
Route::resource('setting', 'SettingController');
Route::resource('comp', 'CompanyController');
// Route::get('comp/all','DashController@all')->name('comp.all');

Route::resource('product', 'ProductController');
Route::get('','dashController@admin')->name('admin.dashbord');
Route::get('/ublode','dashController@orderublode')->name('order.ublode');
Route::get('logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
Route::get('/selectuser/{id}', 'ContactController@selectuser')->name('select.user');



});
//************************************************//
//****************** CMS-ADMIN----User *******************//
//************************************************//
Route::get('/user/month/{file}','dashController@usermonth')->middleware('auth:admin,user')->name('user.month');
Route::resource('category', 'CategoryController')->middleware('auth:admin,user');
Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin')->name('details.month');
// Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin,user')->name('details.month');
Route::get('/categoryproducts/{id}','CategoryController@CategoryProduct')->middleware('auth:admin,user')->name('category.product');
Route::post('details/data','OrderProductController@detailsdata')->middleware('auth:admin,user')->name('details.data');
Route::resource('details', 'orderProductController')->middleware('auth:admin,user');
Route::get('downloadorder/{file}','ImageController@downloadorder')->middleware('auth:admin,user')->name('daw.order');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');

Route::resource('product', 'ProductController')->middleware('auth:admin,user');
Route::resource('ser', 'ServeController')->middleware('auth:admin,user');

Route::get('downloadproduct/{file}','ImageController@downloadproduct')->middleware('auth:admin,user')->name('daw.product');
Route::get('contactresiver/','ContactController@contactresever')->middleware('auth:admin,user')->name('contact.resiver');


Route::resource('order', 'OrderController')->middleware('auth:admin,user');
Route::resource('image', 'ImageController')->middleware('auth:admin,user');
Route::resource('about', 'AboutController')->middleware('auth:admin,user');
Route::resource('contact', 'ContactController')->middleware('auth:admin,user');

////////////////////////////





Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
Route::get('login', 'AdminAuthController@showLoginView')->name('admin.login.view');
Route::post('login', 'AdminAuthController@login')->name('admin.login.post');
Route::view('blocked', 'cms.admin.blocked')->name('cms.admin.blocked');
});


//************************************************//
//****************** CMS-User *******************//
//************************************************//
Route::prefix('cms/user/')->middleware('auth:user')->group(function () {


 Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
       }
       });
Route::get('about','AboutController@userabout')->name('user.about');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');
Route::Post('searchuser','DashController@searchuser')->middleware('auth:user')->name('search.user');

Route::view('/create', 'cms.user.orders.create');
Route::put('/changepaswword/{id}', 'UserController@password')->name('user.password');
Route::view('/changepassword','cms.user.password')->name('user.view.changepassword');
Route::get('','dashController@user')->name('user.dashbord');
Route::get('logout', 'Auth\UserAuthController@logout')->name('user.logout');
Route::get('user/profile','DashController@userprofile')->name('user.profile');
Route::put('user/edit/user/{file}','DashController@edituser')->name('edit.profile');
Route::view('/editprfile','cms.user.editprofile')->name('edit.user.view');
    });


Route::prefix('cms/user/')->namespace('Auth')->group(function () {



Route::get('login', 'UserAuthController@showLoginView')->name('user.login.view');
Route::post('login', 'UserAuthController@login')->name('user.login.post');
Route::view('blocked', 'cms.user.blocked')->name('user.blocked');
Route::get('/register','RegisterControllerUser@reguser')->name('reg.user.view');
Route::post('/post/register','RegisterControllerUser@reguserpost')->name('reg.user.post');

 });

Route::post('/cms/user/searchorder','ProductController@getcode')->name('get.come')->middleware('auth:user');
// Route::post('/user/test','dashController@test')->name('user.test')->middleware('auth:user');
//////////////////////////////////////////////////////////////////////////
Route::get('','WebController@cms')->name('web.index');

Route::get('/comp/all', 'CompanyController@all')->middleware('auth:admin')->name('comp.all');

resources/views/cms/admin/blocked.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>News - Admin | Blocked</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Chango" rel="stylesheet">

	<!-- Custom stlylesheet -->
<link type="text/css" rel="stylesheet" href="{{asset('blocked/style.css')}}" />

</head>

<body>
	<div id="notfound">
		<div class="notfound">
			<div>
				<div class="notfound-404">
					<h1>!</h1>
				</div>
				<h2>Account<br>Blocked</h2>
			</div>
            <p>Your account has been blocked, you don't have access to Ticno Band system <a href="#">Back to Login page</a></p>
        </div>

	</div>
</body>

</html>

resources/views/cms/admin/index.blade.php
@extends('cms.admin.parent')
@section('title','Home')

@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>Dashboard</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="#">الطلبات</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="#">المسوقين</a></li>
                            <li class="breadcrumb-item active" style="font-size: 20px" aria-current="page">الرئيسة</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{route('user.create')}}" class="btn btn-sm btn-primary" style="font-size: 20px" title="">مسوق جديد</a>
                        {{-- <a href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507" class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a> --}}
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center"><i class=" icon-hourglass"> New</i>
                            <h5 class="m-t-20 mb-0">{{$orders->where('status','ublode')->count()}}</h5>
                                <p class="text-muted">طلبات جديدة </p>
                                <a href="{{route('order.ublode')}}" class="btn btn-info btn-round">ذهاب </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center"><i class="icon-calendar "></i>
                                <h5 class="m-t-20 mb-0">{{$month->count()}}</h5>
                                <p class="text-muted">الطلبات الشهرية</p>
                                <a href="{{route('details.month')}}" class="btn btn-info btn-round">ذهاب</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center  "><i class="icon-mouse"></i>
                                <h5 class="m-t-20 mb-0">{{$details->count()}}</h5>
                                <p class="text-muted">إجمالي عدد الطلبيات</p>
                                <a href="{{route('details.index')}}" class="btn btn-info btn-round">ذهاب</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center"><i class=" icon-user"></i>
                                <h5 class="m-t-20 mb-0">{{$users->count()}}</h5>
                                <p class="text-muted">إجمالي المسوقين</p>
                                <a href="{{route('user.index')}}" class="btn btn-info btn-round">ذهاب</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center"><i class="  icon-check"></i>
                                <h5 class="m-t-20 mb-0">{{$details->where('status','success')->count()}}</h5>
                                <p class="text-muted">الطلبات الناجحة </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center"><i class=" icon-grid"></i>
                                <h5 class="m-t-20 mb-0">{{$details->where('status','waiting')->count()}}</h5>
                                <p class="text-muted"> طلبات  قيد الإعتماد</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center  "><i class=" icon-graph"></i>
                            <h5 class="m-t-20 mb-0">{{$month->where('status','success')->sum('total')}}</h5>
                                <p class="text-muted">إجمالي البيع لهذ الشهر</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card w_card3">
                        <div class="body">
                            <div class="text-center"><i class="  icon-calculator"></i>
                                <h5 class="m-t-20 mb-0">{{$details->where('status','success')->sum('total')}}</h5>
                                <p class="text-muted">إجمالي البيع</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                @foreach ($admins as $item)

                <div class="col-lg-3 col-md-12">
                    <div class="card c_grid c_yellow">
                        <div class="body">
                            <div class="circle w60 ">
                                <img class="rounded-circle" width="128px" height="90px" src="{{url('images/admins/'.$item->image)}}" alt="">
                            </div>
                            <div class="text-center mb-5">
                            <h6 class="mt-3 mb-0">{{$item->name}}</h6>
                                <span>{{$item->email}}</span>
                                <span>{{$item->now}}</span>

                                <ul class="mt-3 list-unstyled d-flex justify-content-center">
                                    <li><a class="p-3" target="_blank" href="{{$item->urlfase}}"><i class="fa fa-facebook"></i></a></li>
                                    <li><a class="p-3" target="_blank" href="{{$item->urlwats}}"><i class="fa fa-whatsapp"></i></a></li>
                                    <li><a class="p-3" target="_blank" href="{{$item->urlinsta}}"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
                @endforeach


            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="header">
                            <h2>الطلبات الجديدة</h2>

                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5 mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>اسم المسوق</th>
                                        <th>تاريخ الإنشاء</th>
                                        <th>الحالة</th>
                                        <th>العرض</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($orders->where('status','ublode') as $order)
                                         <tr>
                                       <td class="w60">
                                            <img src="{{url('images/users/'.$order->user->image)}}" data-toggle="tooltip" data-placement="top" title="{{$order->name}}"  class="w35 h35 rounded">
                                                </td>
                                        <td>
                                        <div class="font-15">{{$order->user->name}}</div>
                                        </td>
                                    <td> {{$order->created_at}}</td>
                                        <td><span style="font-size: 17px" class="badge badge-light">لم يتم تسليمها</span></td>
                                        <td>
                                        <a href="{{route('order.show',[$order->id])}}" class="btn btn-info btn-round">عرض</a>
                                        </td>
                                    </tr>
                                    @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/cms/admin/profile.blade.php
@extends('cms.admin.parent')
@section('title','ِAdmin')
@section('content')
 <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>Dashboard</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.dashbord')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('user.index')}}">المسوقين</a></li>
                            <li class="breadcrumb-item active" aria-current="page">الصفحة</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        <a href="javascript:void(0);" class="btn btn-sm btn-primary" title="">إضافة منتج</a>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-4 col-md-12">
                    <div class="card">
                        <div class="body">
                            <div class="media mb-0">
                                @if (Auth::user()->image)
                                  <img class="w60" src="{{url('images/admins/'.Auth::user()->image)}}" alt="">

                                @endif
                                <div class="media-body">
                                    <h5 class="m-0">{{Auth::user()->name}}</h5>
                                    <p class="text-muted mb-0">{{Auth::user()->email}}</p>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <small class="text-muted">رقم الهوية</small>
                            <p class="mb-0">{{Auth::user()->numberid}}</p>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">العنوان</small>
                            <p class="mb-0">{{Auth::user()->address}}</p>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">العمر: </small>
                            <p class="mb-0">{{Auth::user()->age}}</p>
                            </li>

                        </ul>
                    </div>

                </div>
                <div class="col-lg-8 col-md-12">
                    <div class="card">
                        <div class="body">
                        <form method="POST" action="{{route('admin.update',[Auth::user()->id])}}" enctype="multipart/form-data">


                                                    @if ($errors->any())
                                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                        <ul>
                                                            @foreach ($errors->all() as $error)
                                                                <li>{{ $error }}</li>
                                                            @endforeach
                                                        </ul>
                                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                            </div>
                                                @endif
                                                @if (session()->has('message'))
                                                                <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                                                    role="alert">
                                                                    <span> {{ session()->get('message') }}</span>
                                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                            @endif
                                                    @csrf
                                                    @method("PUT")
                            <div class="row clearfix">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                    <label style="font-size: 20px" > الإسم</label>
                                    <input type="text" name="name" value="{{Auth::user()->name}}" style="font-size: 20px" class="form-control" placeholder="الإسم">
                                    </div>
                                </div>
                                    <label style="font-size: 20px" > الصورة الشخصية</label>

                                         <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file" width="590px" height="390px" class="dropify" name="image">
                                            </div>

                                        </div>
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <label style="font-size: 20px" > رقم الهوية</label>
                                    <input type="number" value="{{Auth::user()->numberid}}" name="numberid" class="form-control" style="font-size: 20px" placeholder="رقم الهوية">
                                    </div>
                                </div>
                                    <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <label style="font-size: 20px" >رقم الهاتف</label>
                                    <input type="tel" name="mobile" class="form-control" style="font-size: 20px" value="{{Auth::user()->mobile}}" placeholder="رابط الفيسبوك">
                                    </div>
                                </div>

                                       <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <label style="font-size: 20px" > رابط الفيسبوك</label>
                                    <input type="text" name="urlfase" class="form-control" style="font-size: 20px" value="{{Auth::user()->urlfase}}" placeholder="رابط الفيسبوك">
                                    </div>
                                </div>
                                         <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <label style="font-size: 20px" > رابط الواتساب</label>
                                    <input type="text" name="urlwats" class="form-control" style="font-size: 20px" value="{{Auth::user()->urlwats}}" placeholder="رابط الواتساب">
                                    </div>
                                </div>
                                            <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <label style="font-size: 20px" > رابط الإنستغرام</label>
                                        <input type="text" name="urlinsta" class="form-control" style="font-size: 20px" value="{{Auth::user()->urlinsta}}" placeholder="رابط الإنستغرام">
                                    </div>
                                </div>


                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                            <label style="font-size: 20px" >العمر</label>

                                    <input type="text" class="form-control" style="font-size: 20px" value="{{Auth::user()->age}}" name="age" placeholder="العمر">
                                    </div>
                                </div>
                                       <div class="form-group">
                                <label style="font-size: 20px">الجنس</label>
                                <div class="custom-control custom-radio">
                                    <input class="custom-control-input"  type="radio" id="Male"
                                        name="gender" value="Male"
                                        @if(Auth::user()->gender== 'Male') checked  @endif>
                                    <label  for="Male" class="custom-control-label" style="font-size: 20px">ذكر</label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input class="custom-control-input" type="radio" id="Female"
                                        name="gender" value="Female"
                                        @if(Auth::user()->gender == 'Female') checked @endif>
                                    <label for="Female" class="custom-control-label" style="font-size: 20px">أنثى</label>
                                </div>
                            </div>

                                <div class="col-lg-12 col-md-12">

                                    <div class="form-group">
                                         <label style="font-size: 20px" >العنوان</label>

                                    <textarea rows="2" type="text" style="font-size: 20px" class="form-control" name="address" placeholder="العنوان">{{Auth::user()->address}}</textarea>
                                    </div>
                                </div>
                                 <div class="col-lg-12 col-md-12">

                                    <div class="form-group">
                                         <label style="font-size: 20px" >نبذة شخصية</label>

                                    <textarea rows="2" type="text" style="font-size: 20px" class="form-control" name="now" placeholder="نبذة شخصية">{{Auth::user()->now}}</textarea>
                                    </div>
                                </div>
                                    <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                    <input type="text" class="form-control" style="font-size: 20px" disabled value="{{Auth::user()->view_password}}">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-round btn-primary">تعديل</button> &nbsp;&nbsp;
                        <a href="{{route('admin.dashbord')}}" type="button" class="btn btn-round btn-default">رجوع</a>
                        </form>
                    </div>
                    </div>
                    <div class="card">

                        <div class="body">
                        <form action="{{route('admin.password',[Auth::user()->id])}}" method="POST">

                            @csrf
                            @method("PUT")
                            <div class="row clearfix">

                                <div class="col-lg-12 col-md-12">
                                    <hr>
                                    <h6>تغيير كلمة السر</h6>

                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control" placeholder="كلمة المرور الجديدة">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="confirm" class="form-control" placeholder="تأكيد كلمة المرور">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-round btn-primary">تعديل</button> &nbsp;&nbsp;
                        <a  href="{{route('admin.dashbord')}}"  class="btn btn-round btn-default">رجوع</a>

                    </form>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection