routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Monolog\Handler\RotatingFileHandler;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// Auth::routes();

//************************************************//
//****************** CMS-ADMIN *******************//
//************************************************//

// Route::view('/', 'cms.admin.parent')->name('admin.blocked');

Route::prefix('cms/admin/')->middleware('auth:admin')->group(function () {

    Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
    }
    });



Route::resource('admin', 'AdminController');
Route::put('status/{id}','OrderController@editstatus')->name('status.order');
Route::resource('general', 'GeneralController');
Route::put('/changepaswword/{id}', 'AdminController@password')->name('admin.password');
Route::get('user/details/{details}','UserController@userdetails')->name('user.details');
Route::get('/serves/all','ServeController@all')->name('ser.all');

Route::resource('user', 'UserController');
Route::resource('setting', 'SettingController');
Route::resource('comp', 'CompanyController');
// Route::get('comp/all','DashController@all')->name('comp.all');

Route::resource('product', 'ProductController');
Route::get('','dashController@admin')->name('admin.dashbord');
Route::get('/ublode','dashController@orderublode')->name('order.ublode');
Route::get('logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
Route::get('/selectuser/{id}', 'ContactController@selectuser')->name('select.user');



});
//************************************************//
//****************** CMS-ADMIN----User *******************//
//************************************************//
Route::get('/user/month/{file}','dashController@usermonth')->middleware('auth:admin,user')->name('user.month');
Route::resource('category', 'CategoryController')->middleware('auth:admin,user');
Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin')->name('details.month');
// Route::get('/month/details','dashController@detailsmonth')->middleware('auth:admin,user')->name('details.month');
Route::get('/categoryproducts/{id}','CategoryController@CategoryProduct')->middleware('auth:admin,user')->name('category.product');
Route::post('details/data','OrderProductController@detailsdata')->middleware('auth:admin,user')->name('details.data');
Route::resource('details', 'orderProductController')->middleware('auth:admin,user');
Route::get('downloadorder/{file}','ImageController@downloadorder')->middleware('auth:admin,user')->name('daw.order');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');

Route::resource('product', 'ProductController')->middleware('auth:admin,user');
Route::resource('ser', 'ServeController')->middleware('auth:admin,user');

Route::get('downloadproduct/{file}','ImageController@downloadproduct')->middleware('auth:admin,user')->name('daw.product');
Route::get('contactresiver/','ContactController@contactresever')->middleware('auth:admin,user')->name('contact.resiver');


Route::resource('order', 'OrderController')->middleware('auth:admin,user');
Route::resource('image', 'ImageController')->middleware('auth:admin,user');
Route::resource('about', 'AboutController')->middleware('auth:admin,user');
Route::resource('contact', 'ContactController')->middleware('auth:admin,user');

////////////////////////////





Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
Route::get('login', 'AdminAuthController@showLoginView')->name('admin.login.view');
Route::post('login', 'AdminAuthController@login')->name('admin.login.post');
Route::view('blocked', 'cms.admin.blocked')->name('cms.admin.blocked');
});


//************************************************//
//****************** CMS-User *******************//
//************************************************//
Route::prefix('cms/user/')->middleware('auth:user')->group(function () {


 Route::get('noti', function () {
    $user=Auth::user();
    foreach($user->unreadNotifications as $item){
    $item->markAsRead();
       }
       });
Route::get('about','AboutController@userabout')->name('user.about');
Route::Post('searchAdmin','DashController@searchadmin')->middleware('auth:admin')->name('search.admin');
Route::Post('searchuser','DashController@searchuser')->middleware('auth:user')->name('search.user');

Route::view('/create', 'cms.user.orders.create');
Route::put('/changepaswword/{id}', 'UserController@password')->name('user.password');
Route::view('/changepassword','cms.user.password')->name('user.view.changepassword');
Route::get('','dashController@user')->name('user.dashbord');
Route::get('logout', 'Auth\UserAuthController@logout')->name('user.logout');
Route::get('user/profile','DashController@userprofile')->name('user.profile');
Route::put('user/edit/user/{file}','DashController@edituser')->name('edit.profile');
Route::view('/editprfile','cms.user.editprofile')->name('edit.user.view');
    });


Route::prefix('cms/user/')->namespace('Auth')->group(function () {



Route::get('login', 'UserAuthController@showLoginView')->name('user.login.view');
Route::post('login', 'UserAuthController@login')->name('user.login.post');
Route::view('blocked', 'cms.user.blocked')->name('user.blocked');
Route::get('/register','RegisterControllerUser@reguser')->name('reg.user.view');
Route::post('/post/register','RegisterControllerUser@reguserpost')->name('reg.user.post');

 });

Route::post('/cms/user/searchorder','ProductController@getcode')->name('get.come')->middleware('auth:user');
// Route::post('/user/test','dashController@test')->name('user.test')->middleware('auth:user');
//////////////////////////////////////////////////////////////////////////
Route::get('','WebController@cms')->name('web.index');

Route::get('/comp/all', 'CompanyController@all')->middleware('auth:admin')->name('comp.all');

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    //
}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use App\About;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        if(Auth::guard('admin')->check()){


            $about=About::first();
            // dd($about);
            if($about){
           return redirect()->route('about.show',[$about->id]);

            }
            else
        return view('cms.admin.abouts.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        if(Auth::guard('admin')->check()){


        $request->validate([
            'articale'=>'required',
            'image'=>'required|image',

        ],[
            'articale.required'=>'النص مطلوب',
            'image.image'=>'يجب وضع صورة',
            'image.required'=>'يجب وضع صورة',
        ]);
            $about=new About();
            $about->articale=$request->get('articale');
             if($request->hasFile('image')){
             $imagefile=$request->file('image');
             $imagename=time().' '.$request->name.' '.' '.$imagefile->getClientOriginalName();

             $imagefile->move('images/abouts',$imagename);
             $about->image=$imagename ;
             }
        $save=$about->save();

        if($save){
            Alert::toast('تم الإنشاء بنجاح', 'success');
            return redirect()->route('about.show',[$about->id]);
        }
    }
       else
       return redirect()->route('user.dashbord');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function show($id)

    {
        if(Auth::guard('admin')->check()){
        return view('cms.admin.abouts.show',['about'=>About::find($id)]);

        }
        else
        return redirect()->route('user.dashbord');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::guard('admin')->check()){
  $about=About::first();
  return view('cms.admin.abouts.edit',['about'=>$about]);

        }
           else
           return redirect()->route('user.dashbord');


        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd(443);
        // dd($request->image);
        if(Auth::guard('admin')->check()){


                $request->validate([
                'articale'=>'required',
                'image'=>'nullable|image',

                ],[
                'articale.required'=>'النص مطلوب',
                // 'image.image'=>'يجب وضع صورة',
                ]);
                $about=About::findOrFail($id);
                $about->articale=$request->get('articale');
                if($request->hasFile('image')){
                $imagefile=$request->file('image');
                $imagename=time().' '.$request->name.' '.' '.$imagefile->getClientOriginalName();

                $imagefile->move('images/abouts',$imagename);
                $about->image=$imagename ;
                }
                $save=$about->save();

                if($save){
                Alert::toast('تم التعديل بنجاح', 'success');
                return redirect()->route('about.show',[$about->id]);
                }
            }
               else
               return redirect()->route('user.dashbord');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\About  $about
     * @return \Illuminate\Http\Response
     */
    public function destroy(About $about)
    {
        //
    }
    public function userabout(){
        $about=About::first();
        return view('cms.user.abouts.show',['about'=>$about]);
    }
}

resources/views/cms/admin/abouts/create.blade.php
@extends('cms.admin.parent')
@section('title','حول الشركة')
@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h2>Inbox</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.dashbord')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.show',[Auth::user()->id])}}">الصفحة الشخصية</a></li>
                            <li class="breadcrumb-item active" style="font-size: 20px" aria-current="page">حول الشركة</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="mail-inbox">
                            <div class="mobile-left">
                                <a href="javascript:void(0);" class="btn btn-primary toggle-email-nav"><i class="fa fa-bars"></i></a>
                            </div>

                            <div class="body mail-right check-all-parent">
                                <div class="mail-compose">
                                <form action="{{route('about.store')}}" method="POST" enctype="multipart/form-data">
                                       @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </div>
                        @endif
                        @if (session()->has('message'))
                                        <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                             role="alert">
                                            <span> {{ session()->get('message') }}</span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                         @endif
                                    @csrf

                                    {{-- <input type="text" cols="40" rows="20"  class="form-control"> --}}
                                    {{-- <textarea name="" id="" cols="30" rows="10"></textarea> --}}
                                        <div class="form-group">

                                       <textarea name="articale" class="form-control" id="" cols="30" rows="10">{{old('articale')}}</textarea>
                                        </div>
                                         <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file"  width="590px" height="390px" class="dropify" name="image">
                                            </div>

                                        </div>

                                    <div class="m-t-30 text-right">
                                        <button type="submit" class="btn btn-success btn-round">حفظ</button>

                                         </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/cms/admin/abouts/edit.blade.php
@extends('cms.admin.parent')
@section('title','حول الشركة')
@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h2>Inbox</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.dashbord')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.show',[Auth::user()->id])}}">الصفحة الشخصية</a></li>
                            <li class="breadcrumb-item active" style="font-size: 20px" aria-current="page">حول الشركة</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="mail-inbox">
                            <div class="mobile-left">
                                <a href="javascript:void(0);" class="btn btn-primary toggle-email-nav"><i class="fa fa-bars"></i></a>
                            </div>

                            <div class="body mail-right check-all-parent">
                                <div class="mail-compose">
                                <form action="{{route('about.update',[$about->id])}}" method="POST" enctype="multipart/form-data">
                                       @if ($errors->any())
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </div>
                        @endif
                        @if (session()->has('message'))
                                        <div class="alert {{session()->get('status')}} alert-dismissible fade show"
                                             role="alert">
                                            <span> {{ session()->get('message') }}</span>
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                         @endif
                                    @csrf
                                    @method("PUT")

                                    {{-- <input type="text" cols="40" rows="20"  class="form-control"> --}}
                                    {{-- <textarea name="" id="" cols="30" rows="10"></textarea> --}}
                                        <div class="form-group">

                                       <textarea name="articale" class="form-control" id="" cols="30" rows="10">{{$about->articale}}

                                        </textarea>
                                        <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file"  width="590px" height="390px" class="dropify" name="image">
                                            </div>

                                        </div>
                                        </div>



                                    <div class="m-t-30 text-right">
                                        <button type="submit" class="btn btn-success btn-round">حفظ</button>

                                         </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/cms/admin/abouts/show.blade.php
@extends('cms.admin.parent')
@section('title','حول الشركة')
@section('content')
 <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h2>حول الشركة</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.dashbord')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a style="font-size: 20px" href="{{route('admin.show',[Auth::user()->id])}}">الصفحة الشخصية</a></li>
                            <li class="breadcrumb-item active"  style="font-size: 20px" aria-current="page">حول الشركة</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{route('about.edit',[$about->id])}}" class="btn btn-sm btn-primary btn-round" title="">تعديل</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12">
                    <div class="single-blog">
                        <div class="post-thumb">
                        <a href="#"><img style="height: 380px" width="1024pxs" src="{{url('images/abouts/'.$about->image)}}"   class="img-fluid rounded" alt="Techno Band"></a>
                        </div>
                        <div class="post-content overflow">
                            <h2 class="post-title bold"><a href="#">Techno Band</a></h2>
                        <p>{{$about->articale}}</p>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection